sonar_scan:
  script:
    - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=DDH -Dsonar.sources=. -Dsonar.exclusions=ddh/css/bootstrap**,ddh/js/** -Dsonar.host.url=http://10.64.0.5:9000/ -Dsonar.login=$SONAR_TOKEN