# Generated by Django 2.1.2 on 2018-10-26 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wargames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_name', models.CharField(max_length=50)),
                ('wg_status', models.CharField(choices=[('NS', 'Not Started'), ('ST', 'Started'), ('PA', 'Paused'), ('DO', 'Done')], default='NS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WG_DOCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_doc_title', models.CharField(max_length=50)),
                ('wg_doc_body', models.TextField()),
                ('wg_doc_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WG_VMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_vm_name', models.CharField(max_length=50)),
                ('wg_vm_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='wargames',
            name='wg_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_games.WG_DOCS'),
        ),
        migrations.AddField(
            model_name='wargames',
            name='wg_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_games.WG_VMS'),
        ),
    ]
