# Generated by Django 2.1.1 on 2018-11-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wargames',
            name='wg_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security_games.WG_DOCS'),
        ),
        migrations.AlterField(
            model_name='wargames',
            name='wg_file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='security_games.WG_VMS'),
        ),
    ]
